//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeTerminal
{
    using System;
    using System.Collections.Generic;
    
    public partial class documents
    {
        public int document_id { get; set; }
        public Nullable<int> request_id { get; set; }
        public string file_type { get; set; }
        public string file_path { get; set; }
    
        public virtual requests requests { get; set; }
    }
}
