//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeTerminal
{
    using System;
    using System.Collections.Generic;
    
    public partial class employees
    {
        public employees()
        {
            this.groups = new HashSet<groups>();
            this.requests = new HashSet<requests>();
        }
    
        public int employee_id { get; set; }
        public string full_name { get; set; }
        public Nullable<int> department_id { get; set; }
        public string employee_code { get; set; }
    
        public virtual departments departments { get; set; }
        public virtual ICollection<groups> groups { get; set; }
        public virtual ICollection<requests> requests { get; set; }
    }
}
