//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeTerminal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KeeperPROEntities : DbContext
    {
        public KeeperPROEntities()
            : base("name=KeeperPROEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<departments> departments { get; set; }
        public DbSet<documents> documents { get; set; }
        public DbSet<employees> employees { get; set; }
        public DbSet<groups> groups { get; set; }
        public DbSet<request_statuses> request_statuses { get; set; }
        public DbSet<requests> requests { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<users> users { get; set; }
    }
}
