//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeeperPRO
{
    using System;
    using System.Collections.Generic;
    
    public partial class groups
    {
        public groups()
        {
            this.requests = new HashSet<requests>();
        }
    
        public int group_id { get; set; }
        public string name { get; set; }
        public Nullable<int> department_id { get; set; }
        public Nullable<int> employee_id { get; set; }
        public System.DateTime request_date { get; set; }
    
        public virtual departments departments { get; set; }
        public virtual employees employees { get; set; }
        public virtual ICollection<requests> requests { get; set; }
    }
}
