//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeeperPRO
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public users()
        {
            this.requests = new HashSet<requests>();
        }
    
        public int user_id { get; set; }
        public string full_name { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public System.DateTime birth_date { get; set; }
        public string passport_series { get; set; }
        public string passport_number { get; set; }
        public string login { get; set; }
        public string password_hash { get; set; }
    
        public virtual ICollection<requests> requests { get; set; }
    }
}
