//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeeperPRO.GuardTerminal
{
    using System;
    using System.Collections.Generic;
    
    public partial class departments
    {
        public departments()
        {
            this.employees = new HashSet<employees>();
            this.requests = new HashSet<requests>();
        }
    
        public int department_id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<employees> employees { get; set; }
        public virtual ICollection<requests> requests { get; set; }
    }
}
