//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeeperPRO.GuardTerminal
{
    using System;
    using System.Collections.Generic;
    
    public partial class requests
    {
        public requests()
        {
            this.documents = new HashSet<documents>();
        }
    
        public int request_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> employee_id { get; set; }
        public Nullable<int> department_id { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime end_date { get; set; }
        public string purpose { get; set; }
        public Nullable<int> status_id { get; set; }
        public bool is_group { get; set; }
        public string notes { get; set; }
        public Nullable<System.DateTime> visit_date { get; set; }
    
        public virtual departments departments { get; set; }
        public virtual ICollection<documents> documents { get; set; }
        public virtual employees employees { get; set; }
        public virtual request_statuses request_statuses { get; set; }
        public virtual users users { get; set; }
    }
}
